# Use this file to run the Kalix Transfer service locally with the Kalix payment service.
# Run `mvn kalix:runAll -Dkalix.dev-mode.docker-compose-file=docker-compose-kalix.yml` in transfer-service/kalix to start the transfer service
version: "3"
services:

  kalix-runtime-transfer-service:
    image: gcr.io/kalix-public/kalix-runtime:1.1.31
    container_name: payment-service
    ports:
      - "9001:9001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      HTTP_PORT: 9001
      PERSISTENCE_ENABLED: "false" #when true uncomment volumes above
      JAVA_TOOL_OPTIONS: >
        -Dkalix.dev-mode.service-port-mappings.transfer-service=host.docker.internal:9000
      USER_SERVICE_HOST: ${USER_SERVICE_HOST:-host.docker.internal}
      USER_SERVICE_PORT: 8081