version: "3"
services:

  kalix-runtime:
    image: gcr.io/kalix-public/kalix-runtime:1.1.31
    ports:
      - "9000:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PERSISTENCE_ENABLED: "false" #when true uncomment volumes above
      JAVA_TOOL_OPTIONS: >
        -Dkalix.proxy.eventing.support=kafka
      USER_SERVICE_HOST: ${USER_SERVICE_HOST:-host.docker.internal}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT:-8080}
      # configuring kafka broker used for eventing
      # this assumes that a Kafka service is running!
      BROKER_SERVERS: kafka:29092