POST http://localhost:9000/transfer/12345/on-source-account-debited
Accept: application/json
Content-Type: application/json

{
  "transferId": {
    "uuid": "12345"
  },
  "sourceAccountId": {
    "uuid": "321"
  },
  "amount": {
    "amountInCents": 9999,
    "currency": "USD"
  },
  "result": "SUCCESS"
}

###